// mapData.js

export const districtsData = [
    { value: "71", name: "종로구" },
    { value: "72", name: "중구" },
    { value: "73", name: "광진구/성동구" },
    { value: "74", name: "용산구" },
    { value: "75", name: "동대문구" },
    { value: "76", name: "영등포구" },
    { value: "77", name: "성북구" },
    { value: "78", name: "은평구" },
    { value: "79", name: "강남구" },
    { value: "80", name: "서초구" },
    { value: "81", name: "강서구" },
    { value: "82", name: "강동구" },
    { value: "83", name: "마포구" },
    { value: "84", name: "도봉구" },
    { value: "85", name: "구로구/금천구" },
    { value: "86", name: "노원구" },
    { value: "87", name: "관악구" },
    { value: "88", name: "송파구" },
    { value: "89", name: "양천구" },
    { value: "90", name: "중랑구" },
    { value: "91", name: "동작구" },
    { value: "92", name: "서대문구" },
    { value: "93", name: "강북구" },
  ];
  
  export const centersByDistrictData = {
    '71': [
      {value: '250', text: '대응단'},
      {value: '251', text: '센터1'},
      {value: '252', text: '센터2'},
      {value: '253', text: '센터3'},
      {value: '254', text: '센터4'},
      {value: '255', text: '센터5'},
      {value: '256', text: '센터6'},
      {value: '257', text: '센터7'},
    ],
    '72': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '을지로'},
                    {value: '252', text: '충무로'},
                    {value: '253', text: '신당'},
                    {value: '254', text: '회현'},
                ],
                '73': [
                    {value: '250', text: '대응단'},
                    {value: '252', text: '능동'},
                    {value: '256', text: '중곡'},
                ],
                '74': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '이태원'},
                    {value: '252', text: '후암'},
                    {value: '253', text: '이촌'},
                    {value: '254', text: '서빙고'},
                ],
                '75': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '청량리'},
                    {value: '252', text: '전농'},
                    {value: '253', text: '용두'},
                    {value: '254', text: '휘경'},
                ],
                '76': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '당산'},
                    {value: '252', text: '여의도'},
                    {value: '253', text: '대림'},
                    {value: '254', text: '신길'},
                ],
                '77': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '돈암'},
                    {value: '252', text: '길음'},
                    {value: '253', text: '장위'},
                ],
                '78': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '녹번'},
                    {value: '252', text: '역촌'},
                    {value: '253', text: '수색'},
                ],
                '79': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '영동'},
                    {value: '252', text: '역삼'},
                    {value: '253', text: '수서'},
                    {value: '254', text: '개포'},
                    {value: '255', text: '세곡'},
                ],
                '80': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '방배'},
                    {value: '252', text: '양재'},
                    {value: '253', text: '서초'},
                    {value: '254', text: '잠원'},
                    {value: '255', text: '우면'},
                ],
                '81': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '화곡'},
                    {value: '252', text: '발산'},
                    {value: '253', text: '방화'},
                    {value: '254', text: '개화'},
                    {value: '255', text: '마곡'},
                ],
                '82': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '천호'},
                    {value: '252', text: '고덕'},
                    {value: '253', text: '암사'},
                    {value: '254', text: '길동'},
                    {value: '255', text: '강일'},
                ],
                '83': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '염리'},
                    {value: '252', text: '서교'},
                    {value: '253', text: '성산'},
                    {value: '254', text: '공덕'},
                    {value: '255', text: '상암'},
                ],
                '84': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '도봉'},
                    {value: '252', text: '창동'},
                    {value: '253', text: '쌍문'},
                ],
                '85': [
                    {value: '250', text: '구로대응단'},
                    {value: '251', text: '구로'},
                    {value: '252', text: '공단'},
                    {value: '253', text: '고척'},
                    {value: '254', text: '금천독산'},
                    {value: '255', text: '금천대응단'},
                    {value: '256', text: '신도림'},
                    {value: '257', text: '수궁'},
                ],
                '86': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '상계'},
                    {value: '252', text: '공릉'},
                    {value: '253', text: '월계'},
                    {value: '254', text: '수락'},
                ],
                '87': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '봉천'},
                    {value: '252', text: '신림'},
                    {value: '253', text: '난곡'},
                ],
                '88': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '잠실'},
                    {value: '252', text: '거여'},
                    {value: '253', text: '종합운동장'},
                    {value: '254', text: '방이'},
                    {value: '255', text: '가락'},
                ],
                '89': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '신정'},
                    {value: '252', text: '목동'},
                    {value: '253', text: '신월'},
                    {value: '254', text: '신트리'},
                ],
                '90': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '면목'},
                    {value: '252', text: '망우'},
                    {value: '253', text: '중화'},
                ],
                '91': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '노량진'},
                    {value: '252', text: '상도'},
                    {value: '253', text: '백운'},
                ],
                '92': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '북가좌'},
                    {value: '252', text: '홍은'},
                    {value: '253', text: '북아현'},
                ],
                '93': [
                    {value: '250', text: '대응단'},
                    {value: '251', text: '우이'},
                    {value: '252', text: '미아'},
                    {value: '253', text: '삼각산'},
                ],
                '73': [
                    {value: '251', text: '대응단'},
                    {value: '253', text: '성수'},
                    {value: '254', text: '왕십리'},
                    {value: '255', text: '금호'},
                ],
                '85': [
                    
                ],
    // 다른 지역구의 센터 정보도 여기에 추가할 수 있습니다.
  };